name: Build LaTeX document
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Prerequisite check
        run: ./bin/prerequisite.sh
        shell: bash

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: notes.tex
          latexmk_shell_escape: true

      - name: Fix coding style
        run: |
          apt-get install texlive-extra-utils
          ./bin/format.sh
        shell: bash

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply latexindet changes
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload pdf file
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: notes.pdf
