name: Build LaTeX document
on: [push]
jobs:
  csfix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prerequisite
        run: ./bin/prerequisite.sh
        shell: bash
      
      - name: Setup latex environment
        uses: xu-cheng/latex-action@v2
        
      - name: Codestyle fix
        run: ./bin/format.sh
        shell: bash

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply latexindet changes
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_latex:
    runs-on: ubuntu-latest
    needs: csfix
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Prerequisites
        run: ./bin/prerequisite.sh
        shell: bash
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: notes.tex
          latexmk_shell_escape: true
      
      - name: upload pdf file
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: notes.pdf